name: gtr_services

services:

  #################### STAGE SERVICES ####################

  # MongoDB Stage Service
  mongo_stage:
    build:
      context: .
      dockerfile: server/services/mongo/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminadmin
    ports:
      - "27017:27017"
    volumes:
      - volume_mongo_stage:/data
      - volume_mongo_stage:/var/log/mongodb
      - volume_mongo_stage:/etc/mongod.conf
  
  # MinIO Stage Service
  minio_stage:
    build:
      context: .
      dockerfile: server/services/minio/Dockerfile
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - volume_minio_stage:/data
      - volume_minio_stage:/var/log/minio
  
  
  # Telegram Bot Stage Service
  telegram_stage:
    build:
      context: .
      dockerfile: server/services/telegram_bot/Dockerfile
    restart: unless-stopped
    command: [ "python", "server/services/telegram_bot/App.py" ]
  
  
  # Backend Stage Service
  backend_stage:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: [ "uvicorn", "server.App:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1" ]
  
  
  # ? python .build_web.py
  # Frontend Stage Service
  frontend_stage:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    command: [ "nginx", "-g", "daemon off;" ]

  
  
  #################### PRODUCT SERVICE ####################

  # MongoDB Product Service
  mongo_product:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27027:27017"
  # volumes:
  #   - volume_mongo_product:/data
  #   - volume_mongo_product:/var/log/mongodb
  #   - volume_mongo_product:/etc/mongod.conf


  # MinIO Product Service
  minio_product:
    image: minio/minio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9900:9000"
      - "9901:9001"
    command: server /data --console-address ":9901"
  # volumes:
  #   - volume_minio_product:/data
  #   - volume_minio_product:/var/log/minio



  # Telegram Bot Product Service
  telegram_product:
    build:
      context: .
      dockerfile: server/services/telegram_bot/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: [ "python", "server/services/telegram_bot/App.py" ]


  backend_product:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8800:8000"
    command: [ "uvicorn", "server.App:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4" ]


  # ? python .build_web.py
  frontend_product:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "88:80"
    command: [ "nginx", "-g", "daemon off;" ]


volumes:
  volume_mongo_stage:
  volume_minio_stage:

  volume_mongo_product:
    driver: local
    driver_opts:
      type: none
      device: /mnt/storage/mongo_product
      o: bind
  volume_minio_product:
    driver: local
    driver_opts:
      type: none
      device: /mnt/storage/minio_product
      o: bind







# compose status
# docker compose -f docker-compose.yml ps
