name: gtr_services

services:

  #################### STAGE SERVICES ####################

  # MongoDB Stage Service
  mongo_stage:
    build:
      context: .
      dockerfile: server/services/mongo/Dockerfile
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminadmin
    ports:
      - "27017:27017"
    # volumes:
    #   - /mnt/storage/mongo_stage:/data
    #   - /mnt/storage/mongo_stage/var/log/mongodb:/var/log/mongodb
    #   - /mnt/storage/mongo_stage/etc/mongod.conf:/etc/mongod.conf

    # MinIO Stage Service
  minio_stage:
    build:
      context: .
      dockerfile: server/services/minio/Dockerfile
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # volumes:
    #   - /mnt/storage/minio_stage/data:/data
    #   - /mnt/storage/minio_stage/var/log/minio:/var/log/minio


    # Telegram Bot Stage Service
  telegram_stage:
    build:
      context: .
      dockerfile: server/services/telegram_bot/Dockerfile
    restart: unless-stopped
    environment:
      - BOT_TOKEN=8209910932:AAEYZtLY8sk_X8kfILfyfGeT_Lyaz5Z9hM4
    command: [ "python", "server/services/telegram_bot/App.py" ]

  # Backend Stage Service
  backend_stage:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    command: [ "uvicorn", "server.App:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1" ]
    ports:
      - "8000:8000"

  # ? python .build_web.py
  # Frontend Stage Service
  frontend_stage:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
      - "80:80"

  #################### PRODUCT SERVICE ####################

  # MongoDB Product Service
  mongo_product:
    build:
      context: .
      dockerfile: server/services/mongo/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27027:27017"
    # volumes:
    #   - /mnt/storage/mongo_product:/data
    #   - /mnt/storage/mongo_product/var/log/mongodb:/var/log/mongodb
    #   - /mnt/storage/mongo_product/etc/mongod.conf:/etc/mongod.conf

    # MinIO Product Service
  minio_product:
    build:
      context: .
      dockerfile: server/services/minio/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: server /data --console-address ":9001"
    ports:
      - "9900:9000"
      - "9901:9001"
    # volumes:
    #   - /mnt/storage/minio_product/data:/data
    #   - /mnt/storage/minio_product/var/log/minio:/var/log/minio

    # Telegram Bot Product Service
  telegram_product:
    build:
      context: .
      dockerfile: server/services/telegram_bot/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: [ "python", "server/services/telegram_bot/App.py" ]

  backend_product:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    command: [ "uvicorn", "server.App:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4" ]
    ports:
      - "8800:8000"

  # ? python .build_web.py
  frontend_product:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [ "nginx", "-g", "daemon off;" ]
    ports:
      - "88:80"
  # Add any additional services here
  # compose status
  # docker compose -f docker-compose.yml ps
